### ISSUE TITLE
Compile on dmd 2.060

### ISSUE THREAD

**Issue by simendsjo** [rejectedsoftware/vibe.d#70]
Changes in const correctness and some deprecated functions:

```
/home/simendsjo/code/vibe/vibe.d/bin/../source/vibe/vpm/dependency.d(152): Error: function vibe.vpm.dependency.Dependency.opEquals does not override any function, did you mean 'vibe.vpm.dependency.Dependency.opEquals'

/home/simendsjo/code/vibe/vibe.d/bin/../source/vibe/http/log.d(95): Error: function std.algorithm.indexOf!("a == b",string,string).indexOf is deprecated
/home/simendsjo/code/vibe/vibe.d/bin/../source/vibe/http/log.d(145): Error: function std.algorithm.indexOf!("a == b",string,string).indexOf is deprecated
/home/simendsjo/code/vibe/vibe.d/bin/../source/vibe/data/bson.d(839): Error: function std.algorithm.indexOf!("a == b",immutable(ubyte)[],int).indexOf is deprecated
```
