### ISSUE TITLE
listenTCP and consequently listenHTTPPlain fail with default HTTPServerSettings

### ISSUE THREAD

**Issue by GeorgeSapkin** [rejectedsoftware/vibe.d#904]
`listenTCP` and consequently `listenHTTPPlain` fail with default `HTTPServerSettings` where
```D
bindAddresses = ["::", "0.0.0.0"];
```

So this example from vibe.d start page doesn't work:

```D
auto settings = new HTTPServerSettings;
settings.port = 8080;
listenHTTP(settings, &handleRequest);
```

Specifying either `"::"`, `"0.0.0.0"` or a real IP as bind address resolves the issue.

The exception is
`std.exception.ErrnoException@../../.dub/packages/vibe-d-master/source/vibe/core/drivers/libevent2.d(323): Error binding listening socket (Address already in use)`

`./vibetest(@safe bool vibe.core.drivers.utils.socketEnforce!(bool).socketEnforce(bool, lazy immutable(char)[], immutable(char)[], ulong)+0x48) [0x6a74e4]
./vibetest(vibe.core.drivers.libevent2_tcp.Libevent2TCPListener vibe.core.drivers.libevent2.Libevent2Driver.listenTCP(ushort, void delegate(vibe.core.net.TCPConnection), immutable(char)[], vibe.core.net.TCPListenOptions)+0x1dd) [0x692fa9]
./vibetest(vibe.core.net.TCPListener vibe.core.net.listenTCP(ushort, void delegate(vibe.core.net.TCPConnection), immutable(char)[], vibe.core.net.TCPListenOptions)+0x80) [0x6b7350]`

This happens on Fedora 21 x64. Works on Windows 8.1 x64 though.

**Comment by s-ludwig** [comment]
Not sure when this got fixed, but currently you'll still get an error for the second address, but the HTTP server will still run if listening on *any* of the interfaces  succeeds. In this case, "::" will succeed and the failure of "0.0.0.0" will be ignored.

If I were to choose the defaults today, I'd use `["::1", "127.0.0.1"]` instead, but changing them now would break existing projects. The reason why things are like this is that the initial default was `["0.0.0.0"]`, which was still fine, but then IPv6 support only got added later, and this was the only way to not break backwards compatibility.
