### PR TITLE
Fix Vibe.d nightly (phobos/5355: ISharedAllocator)

### PR DESCRIPTION
**Pull request by wilzbach**
Since 2.074.0 I could observe at least three regressions:
- [ ] `processAllocator` is now `shared` and an `ISharedAllocator` (https://github.com/dlang/phobos/pull/5355)
- [ ] `resolveInternalPointer` accepts now only`const` (https://github.com/dlang/phobos/pull/5321)
- [x] For running `dub test` and its resulting linking errors (https://github.com/dlang/phobos/pull/5432 has been merged).

This is a dirty workaround against the ISharedAllocator changes and allows vibe.d to be built again.

### CODE REVIEW

**Comment by ZombineDev** [comment]
Thanks for doing this! If it's not too much work, can you separate the two workarounds in separate commits and a a link to the respective PRs that introduced the breakage?

**Comment by wilzbach** [comment]
> Thanks for doing this! If it's not too much work, can you separate the two workarounds in separate commits and a a link to the respective PRs that introduced the breakage?

Not at all.
I also reworded the the intro of this PR to reflect the current situation.

**Comment by SerialVelocity** [comment]
@wilzbach @ZombineDev There seems to be another issue now:
```
../../../.dub/packages/vibe-d-0.8.0-beta.7/vibe-d/core/vibe/core/sync.d(143,2): Error: @safe constructor 'vibe.core.sync.LocalTaskSemaphore.this' cannot call @system destructor 'vibe.core.sync.LocalTaskSemaphore.~this
../../../.dub/packages/vibe-d-0.8.0-beta.7/vibe-d/http/vibe/http/server.d(832,2): Error: @safe constructor 'vibe.http.server.HTTPServerRequest.this' cannot call @system destructor 'vibe.http.server.HTTPServerRequest.~this'
```

**Comment by wilzbach** [comment]
> @wilzbach @ZombineDev There seems to be another issue now:

Yeah - isn't that fun? ;-)
Also in Vibe.d 0.7.31-rc.2 [there is/was also an ICE](https://issues.dlang.org/show_bug.cgi?id=17489) - luckily it's just a regression from https://github.com/dlang/phobos/pull/5427 now.

**Comment by MartinNowak** [comment]
The Allocator part would be needed for 2.075.0 to work.

**Comment by wilzbach** [comment]
I just realized that `disposeMultidimensionalArray` and `makeMultidimensionalArray` has been added in 2.074 (https://github.com/dlang/phobos/pull/4982), so it's better to avoid importing them (this lead to the CI build failures).

**Comment by s-ludwig** [comment]
@wilzbach Thanks a lot! I'll merge and then rename the vibe.d version of `processAllocator` to avoid name clashes/confusion.

**Comment by MartinNowak** [comment]
Using the thread-safe `theAllocator` might be an option as well.

**Comment by s-ludwig** [comment]
@MartinNowak: Unfortunately fails (it was actually originally used, but I had to switch to `processAllocator` because of this): https://github.com/dlang/phobos/pull/5519
